# nixpacks.toml (Versi Final)

[phases.setup]
# Menambahkan Python 3.10 secara eksplisit ke lingkungan build,
# bersama dengan dependensi sistem lainnya.
nixPkgs = ["pkgs.python310", "pkgs.glib", "pkgs.mesa"]