services:
  - type: web
    name: calorie-cam
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: FATSECRET_CONSUMER_KEY
        value: $FATSECRET_CONSUMER_KEY
      - key: FATSECRET_CONSUMER_SECRET
        value: $FATSECRET_CONSUMER_SECRET
      - key: OPENROUTER_API_KEY
        value: $OPENROUTER_API_KEY
      - key: ROBOFLOW_MODEL_API_KEY
        value: $ROBOFLOW_MODEL_API_KEY
